version: '3.8'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: n8n
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    ports:
      - 5678:5678   # отладка
      - 8080:8080   # веб-интерфейс n8n (опционально, если будет использоваться)
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: password
      GENERIC_TIMEZONE: Europe/Kyiv
      N8N_BASIC_AUTH_ACTIVE: "false"     # можно включить позже
      N8N_DISABLE_PRODUCTION_MAIN_MENU: "true"
    depends_on:
      postgres:
        condition: service_healthy
